# Generated by Django 3.0.7 on 2021-10-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20210421_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('Donater_id', models.AutoField(primary_key=True, serialize=False)),
                ('Donater_name', models.CharField(default='', max_length=122)),
            ],
        ),
    ]
