
def urlSideMapList():
    urls = [
        # [HREF_LINK,NAME_TO_BE_GIVEN,GRP_ID,SAME_GRP_IN_WEBPAGE,INDI_ID]
        ['/Analyzer/TextAnalyzer/', 'Text editor', 1, 'AT', 0],
        ['/Analyzer/name_sorting/', 'Words Sorting', 1, 'AT', 1],
        ['/Analyzer/Grammar_correction/', 'Grammar Corrector', 1, 'AT', 2],
        ['/Analyzer/Online-Keywords-extractor-from-text/', 'Keyword Extractor', 1, 'AT', 3],
        ['/Analyzer/text-to-base64-converter/', 'text to base64 encoder', 1, 'AT', 4],
        ['/Analyzer/base64-to-text-converter/', 'base64 to text decoder', 1, 'AT', 5],
        ['/Analyzer/text-to-image-converter/', 'text to image converter', 1, 'AT', 6],
        ['/Analyzer/text-to-image-to-text-converter/', 'Image to text converter', 1, 'AT', 7],
        ['/Analyzer/Language-Identifier/', 'Language Identifier', 1, 'AT', 8],
        ['/Analyzer/Caesar-cipher-encoder-decoder/', 'Caesar Cipher encoder/decoder', 1, 'AT', 9],
        ['/Analyzer/playfair-cipher-encoder-decoder/', 'playfair Cipher encoder/decoder', 1, 'AT', 10],

        ['/Conversion/BinaryConverter/', 'Binary Converter', 2, 'CC', 0],
        ['/Conversion/DecimalConverter/', 'Decimal Converter', 2, 'CC', 1],
        ['/Conversion/HexadecimalConverter/', 'Hexadecimal Converter', 2, 'CC', 2],
        ['/Conversion/CurrencyConverter/', 'Currency Converter', 2, 'CC', 3],
        ['/Conversion/infix_to_postfix', 'Infix to Postfix Converter', 2, 'CC', 4],
        ['/Conversion/infix_to_prefix', 'Infix to Prefix Converter', 2, 'CC', 5],
        ['/Conversion/postfix_to_infix', 'Postfix to Infix Converter', 2, 'CC', 6],
        ['/Conversion/prefix_to_postfix', 'Prefix to Postfix Converter', 2, 'CC', 7],
        ['/Conversion/prefix_to_infix', 'Prefix to Infix Converter', 2, 'CC', 8],
        ['/Conversion/cgpa_to_percentage/', 'Cgpa to Percentage Converter', 2, 'CC', 9],
        ['/Conversion/Image_to_base64_Converter/', 'Image to base64 converter', 2, 'CC', 10],
        ['/Conversion/Base64_to_Image_Converter/', 'Base64 to Image converter', 2, 'CC', 11],

        ['/Translator/English_to_hindi/', 'English to Hindi Translator', 3, 'AT', 0],
        ['/Translator/English_to_Marathi/', 'English to Marathi Translator', 3, 'AT', 1],
        ['/Translator/English_to_German/', 'English to German Translator', 3, 'AT', 2],
        ['/Translator/English_to_French/', 'English to French Translator', 3, 'AT', 3],
        ['/Translator/English_to_Arabian/', 'English to Arabian Translator', 3, 'AT', 4],
        ['/Translator/English_to_spanish/', 'English to Spanish Translator', 3, 'AT', 5],
        ['/Translator/English_to_thai/', 'English to Thai Translator', 3, 'AT', 6],
        ['Translator/Hindi_to_English/', 'Hindi to English Translator', 3, 'AT', 7],
        ['/Translator/Hindi_to_Marathi/', 'Hindi to Marathi Translator', 3, 'AT', 8],
        ['/Translator/Hindi_to_German/', 'Hindi to German Translator', 3, 'AT', 9],
        ['/Translator/Hindi_to_French/', 'Hindi to French Translator', 3, 'AT', 10],
        ['/Translator/Hindi_to_Arabian/', 'Hindi to Arabian Translator', 3, 'AT', 11],
        ['/Translator/Hindi_to_Spanish/', 'Hindi to Spanish Translator', 3, 'AT', 12],
        ['/Translator/Hindi_to_Thai/', 'Hindi to Thai Translator', 3, 'AT', 13],


        ['/Calculator/EMI_calculator/', 'EMI Calculator', 4, 'CC', 0],
        ['/Calculator/GCD_calculator/', 'GCD Calculator', 4, 'CC', 1],
        ['/Calculator/BMI_calculator/', 'BMI Calculator', 4, 'CC', 2],
        ['/Calculator/Postfix_calculator/', 'Postfix Calculator', 4, 'CC', 3],
        ['/Calculator/Prefix_calculator/', 'Prefix Calculator', 4, 'CC', 4],
        ['/Calculator/Material-weight-calculator/', 'Material weight Calculator', 4, 'CC', 5],
        ['/Calculator/Linear-regression-calculator/', 'Linear Regression Calculator', 4, 'CC', 6],
        ['/Calculator/HCF-LCM-calculator/', 'Hcf Lcm calculator', 4, 'CC', 7],
    ]
    return urls
